---
- name: Ensure APT HTTPS Transport is installed.
  apt:
    name: apt-transport-https
    state: installed

- name: Add packagecloud.io Varnish apt key.
  apt_key:
    url: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
    state: present

- name: Add packagecloud.io Varnish apt repository.
  apt_repository:
    repo: "deb https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/ubuntu/ {{ ansible_lsb.codename }} main"
    state: present

- name: Install Varnish
  apt: name=varnish state=present
  notify: varnish reload

- name: Ensure varnish config
  template: src=etc/default/varnish dest=/etc/default/varnish owner=root group=root mode=0644
  notify: varnish reload

- name: Ensure varnish default.vcl
  template: src={{ varnish_default_vcl_template }} dest=/etc/varnish/default.vcl owner=root group=root mode=0644
  notify: varnish reload

- name: Enable NCSA-style logging
  template: src=etc/default/varnishncsa dest=/etc/default/varnishncsa owner=root group=root mode=0644
  notify: varnishncsa reload

- name: Ensure Varnish is running
  service: name=varnish state=started
