---

- name: Enable Ondrej PHP repo
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main' state=present

- name: Install PHP 5.6 packages
  apt: name={{ item }} state=present
  with_items:
      - php5.6-common
      - php5.6-cli
      - php5.6-curl
      - php5.6-dev
      - php5.6-gd
      - php5.6-fpm
      - php5.6-json
      - php5.6-opcache
      - php5.6-mysql
      - php-memcached
      - php-xdebug
