---

- name: Enable Ondrej PHP repo
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main' state=present

- name: Install PHP 5.6 packages
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
      - php5.6-common
      - php5.6-cli
      - php5.6-curl
      - php5.6-dev
      - php5.6-gd
      - php5.6-fpm
      - php5.6-json
      - php5.6-opcache
      - php5.6-mysql
      - php5.6-xml
      - php-memcached
      - php-xdebug
      - libyaml-dev

- name: Push out 5.6 php.ini file
  template:
    src: etc/php/5.6/fpm/php.ini
    dest: /etc/php/5.6/fpm/php.ini
  notify: php5.6-fpm restart

- name: Set the max file upload size
  ini_file:
    dest: /etc/php/5.6/fpm/php.ini
    section: "PHP"
    option: "{{ item }}"
    value: "{{ file_upload_max_size }}M"
  with_items:
    - upload_max_filesize
    - post_max_size

- name: Set 5.6 values in php.ini cli
  ini_file:
    dest: /etc/php/5.6/cli/php.ini
    section: "PHP"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'short_open_tag', value: 'On' }

- name: Register Xdebug module
  copy:
    src: etc/php5/mods-available/xdebug.ini
    dest: /etc/php/5.6/mods-available/xdebug.ini
    owner: root
    group: root
    mode: 0644
  notify: php5-fpm restart
  tags: [ 'php' ]

- name: Enable Xdebug module
  command: phpenmod xdebug creates=/etc/php/5.6/fpm/conf.d/20-xdebug.ini
  notify: php5-fpm restart
  tags: [ 'php' ]

- name: Register YAML module
  lineinfile: state=present create=yes dest=/etc/php/5.6/mods-available/yaml.ini line="extension=yaml.so" owner=root group=root mode=0644

- name: Enable YAML module
  command: phpenmod yaml creates=/etc/php/5.6/fpm/conf.d/20-yaml.ini

